---
- hosts: basthost
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  tasks:

  - name: making dirs for ansible files
    ansible.builtin.file:
      path: /home/dusk/ansible/templates
      state: directory
  - name: copying ansible.cfg
    ansible.builtin.copy:
      src: ./ansible.cfg
      dest: /home/dusk/ansible
  - name: copying index.html template
    ansible.builtin.copy:
      src: ./templates/index.html.j2
      dest: /home/dusk/ansible/templates
  - name: copying inventory
    ansible.builtin.copy:
      src: ./inventory.ini
      dest: /home/dusk/ansible
  - name: copying playbook docker
    ansible.builtin.copy:
      src: ./playbook-dock.yml
      dest: /home/dusk/ansible
  - name: copying playbook elas
    ansible.builtin.copy:
      src: ./playbook-elas.yml
      dest: /home/dusk/ansible
  - name: copying playbook web
    ansible.builtin.copy:
      src: ./playbook-web.yml
      dest: /home/dusk/ansible
  - name: copying playbook kibana
    ansible.builtin.copy:
      src: ./playbook-kb.yml
      dest: /home/dusk/ansible