---
- hosts: elastic
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  tasks:

#Installing elastic
  - name: Create elastic search volume
    docker_volume:
      name: esdata
      driver: local
  - name: Create elastic search network
    docker_network:
      name: elas_net
  - name: Start elastic search container
    docker_container:
      name: "elas"
      image: "bitnami/elasticsearch"
      env:
        discovery.type: "single-node"
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        xpack.security.enabled: "true"
        xpack.monitoring.collection.enabled: "true"
        ELASTIC_USERNAME: "elastic"
        ELASTIC_PASSWORD: "elas1234"
      volumes:
      - "esdata:/usr/share/elasticsearch/data"
      ulimits:
      - nofile:65535:65535
      networks:
      - name: "elas_net"
      ports:
        - "9200:9200"
        - "9300:9300"
      state: started
      log_driver: "json-file"
      log_options:
        max-size: "256m"
        max-file: "3"