---
- name: Install docker 
  hosts: docker
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  tasks:
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - ca-certificates
        - lsb-release
        - gnupg
      state: latest
      update_cache: true

  - name: add GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    when: ansible_facts ['distribution'] == "Debian"

  - name: add docker repository to apt
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/debian bookworm stable
      state: present
      filename: docker

  - name: install docker
    ansible.builtin.apt:
      name:
        - docker
        - docker.io
        - docker-compose
        - docker-registry
      state: latest
      update_cache: true

  - name: check docker is active
    service:
      name: docker
      state: started
      enabled: yes

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

  - name: adding user to docker group
    user:
      name: dusk
      groups: docker
      append: yes