---
- hosts: kibana
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  tasks:
  - name: making dirs elk files
    ansible.builtin.file:
      path: /home/dusk/ansible/elk_conf
      state: directory
  - name: copying kiba config
    ansible.builtin.copy:
      src: ./elk_conf/kiba_config.yml
      dest: /home/dusk/ansible/elk_conf   
  - name: Create kibana network
    docker_network:
      name: kiba_net
  - name: Start kibana container
    docker_container:
      name: "kiba"
      image: "kibana:7.17.18"
      volumes:
        - ./ansible/elk_conf/kiba_config.yml:/usr/share/kibana/config/kibana.yml:ro
      networks:
        - name: "kiba_net"
      ports:
        - "5601:5601"
      state: started