---
- name: Using Zabbix collection
  hosts: zabbix
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  collections:
    - community.zabbix
  roles:
    - role: community.zabbix.zabbix_server
      zabbix_server_database: pgsql
      zabbix_server_database_long: pgsql
