---
- hosts: basthost
  become: yes
  tasks:

  - name: making dirs for ansible files
    ansible.builtin.file:
      path: /home/dusk/ansible/templates
      state: directory
  - name: copying ansible.cfg
    ansible.builtin.copy:
      src: ./ansible.cfg
      dest: /home/dusk/ansible
  - name: copying index.html template
    ansible.builtin.copy:
      src: ./templates/index.html.j2
      dest: /home/dusk/ansible/templates
  - name: copying inventory elas
    ansible.builtin.copy:
      src: ./inventory_elas.ini
      dest: /home/dusk/ansible
  - name: copying inventory web
    ansible.builtin.copy:
      src: ./inventory_web.ini
      dest: /home/dusk/ansible
  - name: copying playbook elas
    ansible.builtin.copy:
      src: ./playbook-elas.yml
      dest: /home/dusk/ansible
  - name: copying playbook web
    ansible.builtin.copy:
      src: ./playbook-web.yml
      dest: /home/dusk/ansible