---
- hosts: web
  become: yes
  vars:
    ansible_ssh_user: "dusk"
    ansible_ssh_private_key_file: "/home/dusk/.ssh/dw"
  tasks:

  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_facts ['distribution'] == "Debian"

  - name: changing index.html via jinja2 template
    template:
      src: index.html.j2
      dest: /var/www/html/index.html