---
- hosts: elastic
  become: yes
  tasks:
#Installing docker
  - name: install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    when: ansible_facts ['distribution'] == "Debian"
  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/debian bookworm stable
      state: present
  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  - name: check docker is active
    service:
      name: docker
      state: started
      enabled: yes
  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present
  - name: adding user to docker group
    user:
      name: dusk
      groups: docker
      append: yes
#Installing elastic
  - name: Create elastic search volume
    docker_volume:
      name: esdata
      driver: local
  - name: Create elastic search network
    docker_network:
      name: elas_net
  - name: Start elastic search container
    docker_container:
      name: "elas"
      image: "bitnami/elasticsearch"
      env:
        discovery.type: "single-node"
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        xpack.security.enabled: "true"
        xpack.monitoring.collection.enabled: "true"
        ELASTIC_USERNAME: "elas"
        ELASTIC_PASSWORD: "1234"
      volumes:
      - "esdata:/usr/share/elasticsearch/data"
      ulimits:
      - nofile:65535:65535
      networks:
      - name: "elas_net"
      ports:
        - "9200:9200"
        - "9300:9300"
      state: started
      log_driver: "json-file"
      log_options:
        max-size: "256m"
        max-file: "3"